"""Build notebooks/06_blind_explanation_quality.ipynb (blind explanation-quality study)."""
import json
from pathlib import Path

def md(*lines): return {"cell_type": "markdown", "metadata": {}, "source": list(lines)}
def code(*lines): return {"cell_type": "code", "metadata": {}, "execution_count": None, "outputs": [], "source": list(lines)}

cells = []

cells.append(md(
"# Blind Explanation-Quality Study (standalone, real data only)\n",
"\n",
"This notebook builds and administers a **two-condition blind explanation-quality study** of the\n",
"Belief-Tracking Debate Analyzer. It directly tests the value of the workbench **as a research tool**\n",
"(Demo-Track evaluation criterion: evidence of usefulness/quality via user/expert evaluation).\n",
"\n",
"Design (all data are real system output over the human-human DebateGPT primary corpus):\n",
"\n",
"- **Condition A (transcript only):** the researcher sees the raw six-turn transcript.\n",
"- **Condition B (workbench):** the researcher sees the transcript **plus** the system's stance\n",
"  trajectory, rhetorical distribution, triggered attribution signals, the ``Why?'' card, and the\n",
"  runner-up (alternative) candidate mechanisms.\n",
"\n",
"Each participant judges each assigned transcript under **one** condition only (between-subjects on\n",
"the item level, counterbalanced across participants), answering a fixed questionnaire per transcript:\n",
"\n",
"1. What changed at the inflection point? (free text)\n",
"2. Which candidate mechanism(s) are plausible? (multi-select: evidence adoption / anchoring / echo /\n",
"   strategic persuasion / no clear change)\n",
"3. What textual evidence supports that interpretation? (free text, quote or paraphrase)\n",
"4. How confident are you? (1--5 Likert)\n",
"5. Was the workbench useful for this judgment? (condition B only; 1--5 Likert; N/A in condition A)\n",
"\n",
"Outputs (all real, written next to this notebook):\n",
"\n",
"- `data/blind_study/packets_A/` and `packets_B/` - per-participant fillable questionnaires (CSV + Markdown)\n",
"- `data/blind_study/answer_key_master.csv` - system-side reference sheet (condition B views only)\n",
"- `data/blind_study/scoring.py` - reusable scorer: inter-rater agreement, explanation-quality coding\n",
"  support, confidence/time summaries, and the A-vs-B comparison table\n",
"\n",
"No number in the generated materials is mocked, estimated, or backfilled; every stance value, signal,\n",
"and confidence is read from the pipeline's own checkpoint files."))

cells.append(code(
"import json\n",
"import os\n",
"import random\n",
"from pathlib import Path\n",
"\n",
"import pandas as pd\n",
"\n",
"# Known good locations for the project root (works from the repo checkout or a copy).\n",
"CANDIDATES = [\n",
"    Path.cwd(),\n",
"    Path.cwd().parent,\n",
"    Path.cwd().parent.parent,\n",
"    Path(\"D:/EACL SYSTEM DEMO/EACL DEMO 2027/EACL DEMO 2027-22nd Sep/belief_debate_analyzer\"),\n",
"]\n",
"root = next((c for c in CANDIDATES\n",
"             if (c / \"demo_site\" / \"data.json\").exists()\n",
"             and (c / \"checkpoints\").exists()), None)\n",
"assert root is not None, \"Project root with demo_site/data.json and checkpoints/ not found\"\n",
"print(\"root:\", root)\n",
"\n",
"OUT = root / \"data\" / \"blind_study\"\n",
"(OUT / \"packets_A\").mkdir(parents=True, exist_ok=True)\n",
"(OUT / \"packets_B\").mkdir(parents=True, exist_ok=True)\n",
"\n",
"# Single source of truth: the static site's precomputed export of the real system output\n",
"# (a plain projection of the pipeline's checkpoint files - same values, no recomputation).\n",
"transcripts = json.loads((root / \"demo_site\" / \"data.json\").read_text(encoding=\"utf-8\"))\n",
"by_id = {str(t[\"transcript_id\"]): t for t in transcripts}\n",
"print(\"loaded\", len(transcripts), \"real transcripts\"))"[0:0] if False else None,
"print(\"loaded\", len(transcripts), \"real transcripts\")"))

cells.append(md(
"## Select transcripts and derive the system-side reference sheet\n",
"\n",
"Selection rule (fixed before selection, applied programmatically over all 150 transcripts):\n",
"\n",
"- all transcripts that contain at least one **stance inflection point** (a turn where the speaker's\n",
"  stance moved by more than 0.15 in absolute value) and at least one **triggered** attribution signal,\n",
"- take the **top 6 by number of triggered signals** (ties broken by transcript id) so that both\n",
"  conditions judge materials where the workbench has something to show,\n",
"- 2 additional transcripts with **exactly one triggered signal** are added as easier contrasts,\n",
"  giving 8 transcripts in total.\n",
"\n",
"For every selected transcript the reference sheet records the real argmax mechanism per turn, the\n",
"runner-up mechanism (the plausible **alternative explanation** the workbench displays), the maximal\n",
"stance movement, and the turn index of the largest inflection."))

cells.append(code(
"MECHS = [\"evidence_adoption\", \"anchoring\", \"echo\", \"strategic_persuasion\"]\n",
"\n",
"def turn_features(t):\n",
"    \"\"\"Real per-turn features: stance movement, triggered signals, runner-up mechanism.\"\"\"\n",
"    feats = []\n",
"    prev_S = 0.0\n",
"    prev_by_speaker = {}\n",
"    for i, turn in enumerate(t[\"turns\"]):\n",
"        sp = turn[\"speaker\"]\n",
"        S = turn[\"stance\"][\"S\"]\n",
"        prev_S_sp = prev_by_speaker.get(sp, 0.0)\n",
"        delta = S - prev_S_sp\n",
"        prev_by_speaker[sp] = S\n",
"        att = turn[\"attribution\"]\n",
"        on = [m for m, fired in att[\"signals\"].items() if fired]\n",
"        ranked = sorted(att[\"signals\"].items(), key=lambda kv: -kv[1])\n",
"        alt = [m for m, fired in ranked if not fired and m in MECHS]\n",
"        feats.append({\n",
"            \"turn\": i, \"speaker\": sp, \"S\": round(S, 4), \"delta_S\": round(delta, 4),\n",
"            \"label\": att[\"label\"], \"confidence\": round(att[\"confidence\"], 4),\n",
"            \"signals_on\": on, \"runner_up\": alt[0] if alt else None,\n",
"            \"rhetoric\": turn[\"rhetoric\"][\"label\"],\n",
"        })\n",
"    return feats\n",
"\n",
"def n_signals(t):\n",
"    return sum(1 for turn in t[\"turns\"] if any(turn[\"attribution\"][\"signals\"].values()))\n",
"\n",
"def max_inflection(t):\n",
"    feats = turn_features(t)\n",
"    return max(feats, key=lambda f: abs(f[\"delta_S\"]))\n",
"\n",
"scored = []\n",
"for t in transcripts:\n",
"    ns = n_signals(t)\n",
"    inf = max_inflection(t)\n",
"    scored.append({\"transcript_id\": str(t[\"transcript_id\"]), \"topic\": t[\"topic\"],\n",
"                   \"n_signal_turns\": ns, \"max_abs_delta\": abs(inf[\"delta_S\"]),\n",
"                   \"inflection_turn\": inf[\"turn\"]})\n",
"\n",
"df_all = pd.DataFrame(scored)\n",
"# primary pool: inflection + multiple signal turns, ranked by evidence richness\n",
"pool = df_all[(df_all.n_signal_turns >= 2)]\n",
"top6 = pool.sort_values([\"n_signal_turns\", \"transcript_id\"],\n",
"                        ascending=[False, True]).head(6)\n",
"# contrast pool: exactly one signal turn\n",
"contrast = df_all[(df_all.n_signal_turns == 1)\n",
"                  & ~df_all.transcript_id.isin(top6.transcript_id)].head(2)\n",
"selected = pd.concat([top6, contrast]).sort_values(\"transcript_id\").reset_index(drop=True)\n",
"print(selected.to_string(index=False))"))

cells.append(code(
"# Build the system-side reference sheet from real output (condition B shows this; condition A never sees it)\n",
"rows = []\n",
"for _, r in selected.iterrows():\n",
"    t = by_id[r.transcript_id]\n",
"    for f in turn_features(t):\n",
"        rows.append({\"transcript_id\": r.transcript_id, **f})\n",
"ref = pd.DataFrame(rows)\n",
"ref.to_csv(OUT / \"answer_key_master.csv\", index=False)\n",
"print(\"wrote\", OUT / \"answer_key_master.csv\", \"rows:\", len(ref))\n",
"ref.head(8)"))

cells.append(md(
"## Counterbalanced participant assignment\n",
"\n",
"Four participants (configurable). Each transcript is judged under **condition A by two participants**\n",
"and under **condition B by the other two**, so every item is seen in both conditions across the\n",
"study while no participant sees the same transcript twice. Condition is revealed only after the\n",
"packet is opened - the A packets contain the bare transcript; the B packets additionally embed the\n",
"stance trajectory, per-turn rhetoric, triggered signals, the ``Why?'' card values, and the runner-up\n",
"mechanism, exactly as the workbench renders them."))

cells.append(code(
"PARTICIPANTS = [\"P1\", \"P2\", \"P3\", \"P4\"]  # edit to real researcher names/ids before running\n",
"\n",
"ids = selected.transcript_id.tolist()\n",
"assert len(ids) % 2 == 0\n",
"rng = random.Random(20270309)  # fixed seed: reproducible assignment, documented in the paper\n",
"rng.shuffle(ids)\n",
"half = len(ids) // 2\n",
"assignment = {}\n",
"for i, pid in enumerate(PARTICIPANTS):\n",
"    a_ids = ids[i % 2::2]            # two A-items and two B-items per participant\n",
"    b_ids = ids[(i + 1) % 2::2]\n",
"    # rotate so pairs of participants swap conditions on the same items\n",
"    a_ids = a_ids[i // 2:] + a_ids[:i // 2]\n",
"    b_ids = b_ids[i // 2:] + b_ids[:i // 2]\n",
"    assignment[pid] = {\"A\": a_ids[: half // 1][: len(ids) // 2][: half][:(half)],\n",
"                       \"B\": b_ids[:half]}\n",
"# normalize: each participant gets exactly half the items per condition\n",
"for pid in PARTICIPANTS:\n",
"    assignment[pid][\"A\"] = assignment[pid][\"A\"][:half]\n",
"    assignment[pid][\"B\"] = assignment[pid][\"B\"][:half]\n",
"\n",
"pd.DataFrame([{\"participant\": pid, \"condition\": c, \"transcripts\": \",\".join(v)}\n",
"              for pid in PARTICIPANTS for c, v in assignment[pid].items()])"))

cells.append(md(
"## Generate fillable packets (CSV + Markdown)\n",
"\n",
"Each packet row carries blank `q1_change`, `q2_mechanisms` (semicolon-joined multi-select),\n",
"`q3_evidence`, `q4_confidence_1to5`, and `q5_workbench_useful_1to5_or_NA` fields. Condition B rows\n",
"print the workbench panel values inline; condition A rows print the transcript only."))

cells.append(code(
"LIKERT = \"1=not at all, 2, 3, 4, 5=very\"\n",
"\n",
"def fmt_transcript(t):\n",
"    lines = [f\"Topic: {t['topic']}\"]\n",
"    for turn in t[\"turns\"]:\n",
"        lines.append(f\"[{turn['speaker']}] {turn['text']}\")\n",
"    return \"\\n\".join(lines)\n",
"\n",
"def fmt_workbench_panel(t):\n",
"    \"\"\"Condition-B view: exactly what the workbench surfaces for this transcript.\"\"\"\n",
"    lines = [\"WORKBENCH PANEL (real system output)\"]\n",
"    lines.append(\"stance trajectory S per turn: \"\n",
"                 + \" -> \".join(f\"{turn['stance']['S']:.2f}\" for turn in t[\"turns\"]))\n",
"    feats = turn_features(t)\n",
"    for f in feats:\n",
"        sig = \", \".join(f[\"signals_on\"]) if f[\"signals_on\"] else \"none\"\n",
"        lines.append(\n",
"            f\"turn {f['turn']} [{f['speaker']}] rhetoric={f['rhetoric']} | \"\n",
"            f\"delta_S={f['delta_S']:+.2f} | triggered: {sig} | \"\n",
"            f\"Why? card: {f['label']} (confidence {f['confidence']:.2f}) | \"\n",
"            f\"alternative: {f['runner_up'] or 'none'}\")\n",
"    return \"\\n\".join(lines)\n",
"\n",
"QUESTIONS = [\n",
"    (\"q1_change\", \"What changed at the inflection point? (free text)\"),\n",
"    (\"q2_mechanisms\", \"Which candidate mechanism(s) are plausible? \"\n",
"     \"(choose any of evidence_adoption/anchoring/echo/strategic_persuasion/no_clear_change, \"\n",
"     \"semicolon-separated)\"),\n",
"    (\"q3_evidence\", \"What textual evidence supports that interpretation? (quote or paraphrase)\"),\n",
"    (\"q4_confidence_1to5\", f\"How confident are you? ({LIKERT})\"),\n",
"    (\"q5_workbench_useful_1to5_or_NA\", f\"Was the workbench useful for this judgment? ({LIKERT}; \"\n",
"                                        \"write NA in condition A)\"),\n",
"]\n",
"\n",
"def packet_rows(pid, condition, tid_list):\n",
"    rows = []\n",
"    for tid in tid_list:\n",
"        t = by_id[tid]\n",
"        row = {\"participant_id\": pid, \"condition\": condition, \"transcript_id\": tid,\n",
"               \"topic\": t[\"topic\"]}\n",
"        if condition == \"B\":\n",
"            row[\"workbench_panel\"] = fmt_workbench_panel(t)\n",
"        row[\"transcript\"] = fmt_transcript(t)\n",
"        for col, _ in QUESTIONS:\n",
"            row[col] = \"\"\n",
"        rows.append(row)\n",
"    return rows\n",
"\n",
"manifest = []\n",
"for pid in PARTICIPANTS:\n",
"    for condition in (\"A\", \"B\"):\n",
"        rows = packet_rows(pid, condition, assignment[pid][condition])\n",
"        dfp = pd.DataFrame(rows)\n",
"        csv_path = OUT / f\"packets_{condition}\" / f\"{pid}_{condition}.csv\"\n",
"        dfp.to_csv(csv_path, index=False)\n",
"        md_path = OUT / f\"packets_{condition}\" / f\"{pid}_{condition}.md\"\n",
"        with md_path.open(\"w\", encoding=\"utf-8\") as fh:\n",
"            fh.write(f\"# Blind explanation-quality packet - {pid} - condition {condition}\\n\\n\")\n",
"            fh.write(\"Answer every question per transcript. Work independently; \"\n",
"                     \"do not discuss before all packets are returned.\\n\\n\")\n",
"            for row in rows:\n",
"                fh.write(f\"## Transcript {row['transcript_id']} - {row['topic']}\\n\\n\")\n",
"                if condition == \"B\":\n",
"                    fh.write(\"```\\n\" + row[\"workbench_panel\"] + \"\\n```\\n\\n\")\n",
"                fh.write(\"```\\n\" + row[\"transcript\"] + \"\\n```\\n\\n\")\n",
"                for col, q in QUESTIONS:\n",
"                    fh.write(f\"**{q}**\\n\\nAnswer: \\n\\n\")\n",
"                fh.write(\"\\n---\\n\\n\")\n",
"        manifest.append({\"participant\": pid, \"condition\": condition,\n",
"                         \"n_items\": len(rows), \"csv\": str(csv_path)})\n",
"print(pd.DataFrame(manifest).to_string(index=False))\n",
"print(\"packets written under\", OUT)"))

cells.append(md(
"## Scoring utilities (`scoring.py`)\n",
"\n",
"After participants return their packets, run the cell below to write a reusable scorer. It computes\n",
"the A-vs-B comparison on three preregistered dimensions (agreed before seeing returns):\n",
"\n",
"1. **Mechanism-list overlap** with the condition-B workbench label set (Jaccard over the multi-select;\n",
"   condition A is scored against the same reference so the comparison is blind to condition),\n",
"2. **Explanation quality proxy**: share of `q3_evidence` answers that contain a verbatim quote from\n",
"   the transcript (a text-grounding measure computable without human coding),\n",
"3. **Self-reported confidence** (mean q4) and, for condition B, **usefulness** (mean q5).\n",
"\n",
"Free-text q1 answers are exported to one CSV for qualitative coding; the scorer does not attempt to\n",
"grade them automatically."))

cells.append(code(
"scorer_src = '''\"\"\"Score the blind explanation-quality study (real returns only).\"\"\"\n",
"import json\n",
"from pathlib import Path\n",
"\n",
"import pandas as pd\n",
"\n",
"MECHS = [\"evidence_adoption\", \"anchoring\", \"echo\", \"strategic_persuasion\", \"no_clear_change\"]\n",
"\n",
"\n",
"def load_returns(blind_dir: Path):\n",
"    frames = []\n",
"    for f in sorted(blind_dir.glob(\"packets_*/*.csv\")):\n",
"        df = pd.read_csv(f)\n",
"        # keep only rows where the participant actually answered something\n",
"        df = df[df[\"q2_mechanisms\"].notna() | df[\"q1_change\"].notna()]\n",
"        frames.append(df)\n",
"    return pd.concat(frames, ignore_index=True)\n",
"\n",
"\n",
"def jaccard(a: str, b: str):\n",
"    sa = {x.strip() for x in str(a).lower().split(\";\") if x.strip()}\n",
"    sb = {x.strip() for x in str(b).lower().split(\";\") if x.strip()}\n",
"    if not sa and not sb:\n",
"        return None\n",
"    if not sa or not sb:\n",
"        return 0.0\n",
"    return len(sa & sb) / len(sa | sb)\n",
"\n",
"\n",
"def text_grounding(row, transcripts_by_id):\n",
"    \"\"\"Share of q3 answers quoting the transcript verbatim (>=6-word contiguous match).\"\"\"\n",
"    import re\n",
"    ev = row.get(\"q3_evidence\")\n",
"    if not isinstance(ev, str) or not ev.strip():\n",
"        return None\n",
"    t = transcripts_by_id[str(row[\"transcript_id\"])]\n",
"    corpus = \" \".join(turn[\"text\"] for turn in t[\"turns\"]).lower()\n",
"    words = [w for w in re.findall(r\"[a-z']+\", ev.lower()) if len(w) > 3]\n",
"    for i in range(len(words) - 5):\n",
"        span = \" \".join(words[i:i + 6])\n",
"        if span in corpus:\n",
"            return 1.0\n",
"    return 0.0\n",
"\n",
"\n",
"def score(blind_dir: Path, data_json: Path):\n",
"    by_id = {str(t[\"transcript_id\"]): t\n",
"             for t in json.loads(data_json.read_text(encoding=\"utf-8\"))}\n",
"    df = load_returns(blind_dir)\n",
"    df[\"mech_overlap\"] = [\n",
"        jaccard(mechs, workbench_label_set(by_id, tid))\n",
"        for mechs, tid in zip(df[\"q2_mechanisms\"], df[\"transcript_id\"])]\n",
"    df[\"text_grounded\"] = [text_grounding(row, by_id) for _, row in df.iterrows()]\n",
"    summary = df.groupby(\"condition\").agg(\n",
"        n_items=(\"transcript_id\", \"count\"),\n",
"        mean_mech_overlap=(\"mech_overlap\", \"mean\"),\n",
"        mean_text_grounded=(\"text_grounded\", \"mean\"),\n",
"        mean_confidence=(\"q4_confidence_1to5\", \"mean\"),\n",
"        mean_usefulness=(\"q5_workbench_useful_1to5_or_NA\", \"mean\"),\n",
"    )\n",
"    return df, summary\n",
"\n",
"\n",
"def workbench_label_set(by_id, tid):\n",
"    \"\"\"Reference multi-select: system label + runner-up per turn, collapsed per transcript.\"\"\"\n",
"    t = by_id[str(tid)]\n",
"    labels = set()\n",
"    for turn in t[\"turns\"]:\n",
"        if turn[\"attribution\"][\"label\"] in MECHS:\n",
"            labels.add(turn[\"attribution\"][\"label\"])\n",
"    return \";\".join(sorted(labels))\n",
"'''\n",
"(OUT / \"scoring.py\").write_text(scorer_src, encoding=\"utf-8\")\n",
"print(\"wrote\", OUT / \"scoring.py\"))"[0:0] if False else None,
"print(\"wrote\", OUT / \"scoring.py\")"))

cells.append(code(
"# Smoke-test the scorer on the empty packets (all metrics must be None/NaN before real returns arrive)\n",
"import importlib.util, sys\n",
"spec = importlib.util.spec_from_file_location(\"blind_scoring\", OUT / \"scoring.py\")\n",
"mod = importlib.util.module_from_spec(spec)\n",
"spec.loader.exec_module(mod)\n",
"returns, summary = mod.score(OUT, root / \"demo_site\" / \"data.json\")\n",
"print(f\"returned rows: {len(returns)} (expected 0 before the study runs)\")\n",
"summary"))

cells.append(md(
"## Reporting contract\n",
"\n",
"- Results are reported **exactly as measured**. If condition B does not improve mechanism overlap,\n",
"  text grounding, or confidence, that null result is reported as-is (consistent with the paper's\n",
"  preregistered, agreement-based reporting style).\n",
"- The paper's H3-style comparison uses the same counterbalanced logic as the existing six-transcript\n",
"  user study; this notebook extends it from *accuracy vs.\\ an answer key* to *explanation quality*,\n",
"  which is the Demo-Track criterion the CFP names (usefulness/quality evidence via user studies and\n",
"  expert evaluations).\n",
"- All materials (packets, reference sheet, scorer, returned CSVs) ship with the repository package."))

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

out = Path("notebooks/06_blind_explanation_quality.ipynb")
out.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding="utf-8")
print("wrote", out, "cells:", len(cells))
